# -*- coding: utf-8 -*-
# File: config.py

__author__ = """Simples Consultoria <products@simplesconsultoria.com.br>"""
__docformat__ = 'plaintext'

PROJECTNAME = 'sc.social.like'

# Retrieved from https://www.facebook.com/translations/FacebookLocales.xml 
# on 2011-07-12 16:06-0300
FB_LOCALES = ['af_ZA',
              'ar_AR',
              'ay_BO',
              'az_AZ',
              'be_BY',
              'bg_BG',
              'bn_IN',
              'bs_BA',
              'ca_ES',
              'ck_US',
              'cs_CZ',
              'cy_GB',
              'da_DK',
              'de_DE',
              'el_GR',
              'en_GB',
              'en_PI',
              'en_UD',
              'en_US',
              'eo_EO',
              'es_CL',
              'es_CO',
              'es_ES',
              'es_LA',
              'es_MX',
              'es_VE',
              'et_EE',
              'eu_ES',
              'fa_IR',
              'fb_FI',
              'fb_LT',
              'fi_FI',
              'fo_FO',
              'fr_CA',
              'fr_FR',
              'ga_IE',
              'gl_ES',
              'gn_PY',
              'gu_IN',
              'he_IL',
              'hi_IN',
              'hr_HR',
              'hu_HU',
              'hy_AM',
              'id_ID',
              'is_IS',
              'it_IT',
              'ja_JP',
              'jv_ID',
              'ka_GE',
              'kk_KZ',
              'km_KH',
              'kn_IN',
              'ko_KR',
              'ku_TR',
              'la_VA',
              'li_NL',
              'lt_LT',
              'lv_LV',
              'mg_MG',
              'mk_MK',
              'ml_IN',
              'mn_MN',
              'mr_IN',
              'ms_MY',
              'mt_MT',
              'nb_NO',
              'ne_NP',
              'nl_BE',
              'nl_NL',
              'nn_NO',
              'pa_IN',
              'pl_PL',
              'ps_AF',
              'pt_BR',
              'pt_PT',
              'qu_PE',
              'rm_CH',
              'ro_RO',
              'ru_RU',
              'sa_IN',
              'se_NO',
              'sk_SK',
              'sl_SI',
              'so_SO',
              'sq_AL',
              'sr_RS',
              'sv_SE',
              'sw_KE',
              'sy_SY',
              'ta_IN',
              'te_IN',
              'tg_TJ',
              'th_TH',
              'tl_PH',
              'tl_ST',
              'tr_TR',
              'tt_RU',
              'uk_UA',
              'ur_PK',
              'uz_UZ',
              'vi_VN',
              'xh_ZA',
              'yi_DE',
              'zh_CN',
              'zh_HK',
              'zh_TW',
              'zu_ZA',]